name: wizer
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  dio: ^5.4.0
  connectivity_plus: ^5.0.2
  shared_preferences: ^2.2.2
  firebase_core: ^2.24.2
  flutter_svg: ^2.0.9
  carousel_slider: ^4.0.0
  otp_text_field: ^1.1.3
  flutter_rating_bar: ^4.0.1


  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/svgs/
    - assets/pngs/
    - assets/images/
#    - assets/json/
  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Regular.ttf
        - asset: fonts/Raleway-SemiBold.ttf
          weight: 700
        - asset: fonts/Raleway-Italic.ttf
          style: italic
